[2024-06-16 19:24:36,350] - [ WARNING] - [   root] - [bfaf3ea1-2695-45c8-aa61-c2d9133a9306] - Connection established
[2024-06-16 19:24:42,180] - [    INFO] - [   root] - [bfaf3ea1-2695-45c8-aa61-c2d9133a9306] - User 249824300 is a subscriber of the channel @needify_test_channel
[2024-06-16 19:50:12,024] - [ WARNING] - [   root] - [c73e4ea7-d281-421f-a5a0-faf30320df78] - Connection established
[2024-06-16 19:52:50,569] - [ WARNING] - [   root] - [2f880a1f-f799-46cd-8a68-841c9b730839] - Connection established
[2024-06-16 20:09:57,636] - [ WARNING] - [   root] - [188ae419-6798-471b-bcd6-ad8ab3393b5c] - Connection established
[2024-06-16 20:15:03,012] - [ WARNING] - [   root] - [4ce6ee50-6734-415e-ae03-b7fa6ca44733] - Connection established
[2024-06-16 20:15:16,890] - [ WARNING] - [   root] - [73c9b843-891e-4a7f-b3c6-c321cad7e1f4] - Connection established
[2024-06-16 20:16:00,954] - [ WARNING] - [   root] - [c5affe1c-16ac-4a00-b97a-43195e8c7d58] - Connection established
[2024-06-16 20:16:03,852] - [    INFO] - [   root] - [c5affe1c-16ac-4a00-b97a-43195e8c7d58] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:16:28,571] - [ WARNING] - [   root] - [91b2e8aa-263e-4cf7-9012-76236d4ad153] - Connection established
[2024-06-16 20:16:29,985] - [    INFO] - [   root] - [91b2e8aa-263e-4cf7-9012-76236d4ad153] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:17:00,099] - [ WARNING] - [   root] - [850ac53f-5343-4b4f-8136-5a5f41418129] - Connection established
[2024-06-16 20:17:02,052] - [    INFO] - [   root] - [850ac53f-5343-4b4f-8136-5a5f41418129] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:17:45,485] - [ WARNING] - [   root] - [a9afeaed-5312-4824-adf0-751d8d8774db] - Connection established
[2024-06-16 20:17:48,128] - [    INFO] - [   root] - [a9afeaed-5312-4824-adf0-751d8d8774db] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:21:42,301] - [ WARNING] - [   root] - [9aa2f85d-dda0-4c40-9513-6a8079aef19a] - Starting connection
[2024-06-16 20:21:42,302] - [ WARNING] - [   root] - [9aa2f85d-dda0-4c40-9513-6a8079aef19a] - Connection established
[2024-06-16 20:22:06,863] - [    INFO] - [   root] - [9aa2f85d-dda0-4c40-9513-6a8079aef19a] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:23:06,501] - [ WARNING] - [   root] - [c502ee7d-bcdc-453e-b84d-de962b140eb4] - Starting connection
[2024-06-16 20:23:06,502] - [ WARNING] - [   root] - [c502ee7d-bcdc-453e-b84d-de962b140eb4] - Connection established
[2024-06-16 20:23:13,068] - [    INFO] - [   root] - [c502ee7d-bcdc-453e-b84d-de962b140eb4] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:24:43,284] - [ WARNING] - [   root] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Starting connection
[2024-06-16 20:24:43,285] - [ WARNING] - [   root] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Connection established
[2024-06-16 20:24:43,285] - [    INFO] - [aiogram.dispatcher] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Start polling
[2024-06-16 20:24:43,329] - [    INFO] - [aiogram.dispatcher] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:24:50,139] - [    INFO] - [   root] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:24:50,140] - [    INFO] - [aiogram.event] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Update id=396828924 is not handled. Duration 4 ms by bot id=7025856738
[2024-06-16 20:24:50,140] - [   ERROR] - [aiogram.event] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Cause exception while process update id=396828924 by bot id=7025856738
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/referral/handlers.py", line 28, in send_welcome
    referral_button = InlineKeyboardButton('Share Referral Link', callback_data='share_referral')
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
[2024-06-16 20:25:49,514] - [ WARNING] - [aiogram.dispatcher] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Received SIGINT signal
[2024-06-16 20:25:49,516] - [    INFO] - [aiogram.dispatcher] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:25:49,517] - [    INFO] - [aiogram.dispatcher] - [e29a0b5a-cdde-49a8-81a5-f15048b3b1e3] - Polling stopped
[2024-06-16 20:25:51,490] - [ WARNING] - [   root] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Starting connection
[2024-06-16 20:25:51,490] - [ WARNING] - [   root] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Connection established
[2024-06-16 20:25:51,490] - [    INFO] - [aiogram.dispatcher] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Start polling
[2024-06-16 20:25:51,539] - [    INFO] - [aiogram.dispatcher] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:25:56,846] - [    INFO] - [   root] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:25:56,846] - [    INFO] - [aiogram.event] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Update id=396828925 is not handled. Duration 3 ms by bot id=7025856738
[2024-06-16 20:25:56,846] - [   ERROR] - [aiogram.event] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Cause exception while process update id=396828925 by bot id=7025856738
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/referral/handlers.py", line 28, in send_welcome
    referral_button = InlineKeyboardButton('Share Referral Link', callback_data='share_referral')
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
[2024-06-16 20:26:17,452] - [ WARNING] - [aiogram.dispatcher] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Received SIGINT signal
[2024-06-16 20:26:17,454] - [    INFO] - [aiogram.dispatcher] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:26:17,455] - [    INFO] - [aiogram.dispatcher] - [d5227be7-5abd-47f1-ba9c-5dfdca571041] - Polling stopped
[2024-06-16 20:26:20,466] - [ WARNING] - [   root] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Starting connection
[2024-06-16 20:26:20,466] - [ WARNING] - [   root] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Connection established
[2024-06-16 20:26:20,467] - [    INFO] - [aiogram.dispatcher] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Start polling
[2024-06-16 20:26:20,504] - [    INFO] - [aiogram.dispatcher] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:26:24,722] - [    INFO] - [   root] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:26:24,886] - [    INFO] - [aiogram.event] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Update id=396828926 is handled. Duration 168 ms by bot id=7025856738
[2024-06-16 20:26:29,676] - [    INFO] - [aiogram.event] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Update id=396828927 is handled. Duration 231 ms by bot id=7025856738
[2024-06-16 20:27:35,700] - [    INFO] - [aiogram.event] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Update id=396828928 is handled. Duration 236 ms by bot id=7025856738
[2024-06-16 20:27:37,292] - [    INFO] - [aiogram.event] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Update id=396828929 is handled. Duration 131 ms by bot id=7025856738
[2024-06-16 20:28:09,768] - [ WARNING] - [aiogram.dispatcher] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Received SIGINT signal
[2024-06-16 20:28:09,769] - [    INFO] - [aiogram.dispatcher] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:28:09,769] - [    INFO] - [aiogram.dispatcher] - [86587c54-a83e-4aa1-8dcb-3f32b0444111] - Polling stopped
[2024-06-16 20:28:12,278] - [ WARNING] - [   root] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Starting connection
[2024-06-16 20:28:12,278] - [ WARNING] - [   root] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Connection established
[2024-06-16 20:28:12,278] - [    INFO] - [aiogram.dispatcher] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Start polling
[2024-06-16 20:28:12,325] - [    INFO] - [aiogram.dispatcher] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:28:14,646] - [    INFO] - [   root] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:28:14,821] - [    INFO] - [aiogram.event] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Update id=396828930 is handled. Duration 177 ms by bot id=7025856738
[2024-06-16 20:28:26,459] - [    INFO] - [   root] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:28:26,524] - [    INFO] - [aiogram.event] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Update id=396828931 is handled. Duration 66 ms by bot id=7025856738
[2024-06-16 20:28:34,968] - [ WARNING] - [aiogram.dispatcher] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Received SIGINT signal
[2024-06-16 20:28:34,971] - [    INFO] - [aiogram.dispatcher] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:28:34,972] - [    INFO] - [aiogram.dispatcher] - [8ce86c13-2c3e-4b8b-9a6e-7eba3e274681] - Polling stopped
[2024-06-16 20:28:36,793] - [ WARNING] - [   root] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Starting connection
[2024-06-16 20:28:36,794] - [ WARNING] - [   root] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Connection established
[2024-06-16 20:28:36,794] - [    INFO] - [aiogram.dispatcher] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Start polling
[2024-06-16 20:28:36,840] - [    INFO] - [aiogram.dispatcher] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:28:38,522] - [    INFO] - [   root] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:28:38,710] - [    INFO] - [aiogram.event] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Update id=396828932 is handled. Duration 190 ms by bot id=7025856738
[2024-06-16 20:32:00,543] - [ WARNING] - [aiogram.dispatcher] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Received SIGINT signal
[2024-06-16 20:32:00,546] - [    INFO] - [aiogram.dispatcher] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:32:00,546] - [    INFO] - [aiogram.dispatcher] - [ccd187da-4b51-4cd7-b06a-47a0ff905781] - Polling stopped
[2024-06-16 20:32:02,693] - [ WARNING] - [   root] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Starting connection
[2024-06-16 20:32:02,693] - [ WARNING] - [   root] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Connection established
[2024-06-16 20:32:02,693] - [    INFO] - [aiogram.dispatcher] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Start polling
[2024-06-16 20:32:02,734] - [    INFO] - [aiogram.dispatcher] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:32:05,433] - [    INFO] - [   root] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:32:05,623] - [    INFO] - [aiogram.event] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Update id=396828933 is handled. Duration 192 ms by bot id=7025856738
[2024-06-16 20:32:07,677] - [    INFO] - [aiogram.event] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Update id=396828934 is not handled. Duration 2 ms by bot id=7025856738
[2024-06-16 20:32:07,678] - [   ERROR] - [aiogram.event] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Cause exception while process update id=396828934 by bot id=7025856738
RuntimeError: This method is not mounted to a any bot instance, please call it explicilty with bot instance `await bot(method)`
or mount method to a bot instance `method.as_(bot)` and then call it `await method()`
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/referral/handlers.py", line 41, in process_callback_share_referral
    invite_link = await CreateChatInviteLink(chat_id=env_config.telegram.CHANNEL_ID)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/methods/base.py", line 89, in __await__
    raise RuntimeError(
RuntimeError: This method is not mounted to a any bot instance, please call it explicilty with bot instance `await bot(method)`
or mount method to a bot instance `method.as_(bot)` and then call it `await method()`
[2024-06-16 20:34:05,699] - [ WARNING] - [aiogram.dispatcher] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Received SIGINT signal
[2024-06-16 20:34:05,701] - [    INFO] - [aiogram.dispatcher] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:34:05,701] - [    INFO] - [aiogram.dispatcher] - [aa577552-da45-4bb9-b4ae-104d2243c56e] - Polling stopped
[2024-06-16 20:34:07,658] - [ WARNING] - [   root] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Starting connection
[2024-06-16 20:34:07,658] - [ WARNING] - [   root] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Connection established
[2024-06-16 20:34:07,659] - [    INFO] - [aiogram.dispatcher] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Start polling
[2024-06-16 20:34:07,707] - [    INFO] - [aiogram.dispatcher] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:34:12,051] - [    INFO] - [   root] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:34:12,217] - [    INFO] - [aiogram.event] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Update id=396828935 is handled. Duration 169 ms by bot id=7025856738
[2024-06-16 20:34:13,564] - [    INFO] - [aiogram.event] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Update id=396828936 is handled. Duration 284 ms by bot id=7025856738
[2024-06-16 20:34:18,735] - [    INFO] - [aiogram.event] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Update id=396828937 is handled. Duration 157 ms by bot id=7025856738
[2024-06-16 20:37:21,839] - [ WARNING] - [aiogram.dispatcher] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Received SIGINT signal
[2024-06-16 20:37:21,841] - [    INFO] - [aiogram.dispatcher] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:37:21,841] - [    INFO] - [aiogram.dispatcher] - [4f54dd2e-3afc-4d4f-84ab-d6cc88ab4e33] - Polling stopped
[2024-06-16 20:37:24,226] - [ WARNING] - [   root] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Starting connection
[2024-06-16 20:37:24,226] - [ WARNING] - [   root] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Connection established
[2024-06-16 20:37:24,226] - [    INFO] - [aiogram.dispatcher] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Start polling
[2024-06-16 20:37:24,274] - [    INFO] - [aiogram.dispatcher] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:37:30,349] - [    INFO] - [   root] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:37:30,530] - [    INFO] - [aiogram.event] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Update id=396828938 is handled. Duration 184 ms by bot id=7025856738
[2024-06-16 20:37:32,250] - [    INFO] - [aiogram.event] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Update id=396828939 is not handled. Duration 1 ms by bot id=7025856738
[2024-06-16 20:37:32,250] - [   ERROR] - [aiogram.event] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Cause exception while process update id=396828939 by bot id=7025856738
AttributeError: 'TelegramConfig' object has no attribute 'CHANNEL_ID'
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 803, in __getattr__
    return pydantic_extra[item]
KeyError: 'CHANNEL_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/referral/handlers.py", line 43, in process_callback_share_referral
    referral_link = f"https://t.me/{env_config.telegram.CHANNEL_ID}?start={user_id}"
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 805, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'TelegramConfig' object has no attribute 'CHANNEL_ID'
[2024-06-16 20:37:40,156] - [ WARNING] - [aiogram.dispatcher] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Received SIGINT signal
[2024-06-16 20:37:40,158] - [    INFO] - [aiogram.dispatcher] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:37:40,158] - [    INFO] - [aiogram.dispatcher] - [fc236488-b5b0-474b-afe2-0a8e6838e71b] - Polling stopped
[2024-06-16 20:37:42,248] - [ WARNING] - [   root] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Starting connection
[2024-06-16 20:37:42,248] - [ WARNING] - [   root] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Connection established
[2024-06-16 20:37:42,248] - [    INFO] - [aiogram.dispatcher] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Start polling
[2024-06-16 20:37:42,298] - [    INFO] - [aiogram.dispatcher] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:37:46,017] - [    INFO] - [aiogram.event] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Update id=396828940 is handled. Duration 251 ms by bot id=7025856738
[2024-06-16 20:38:10,171] - [ WARNING] - [aiogram.dispatcher] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Received SIGINT signal
[2024-06-16 20:38:10,173] - [    INFO] - [aiogram.dispatcher] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:38:10,174] - [    INFO] - [aiogram.dispatcher] - [34ca2fd8-783e-43b5-81ae-15e54589ef1a] - Polling stopped
[2024-06-16 20:38:12,621] - [ WARNING] - [   root] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Starting connection
[2024-06-16 20:38:12,621] - [ WARNING] - [   root] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Connection established
[2024-06-16 20:38:12,622] - [    INFO] - [aiogram.dispatcher] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Start polling
[2024-06-16 20:38:12,664] - [    INFO] - [aiogram.dispatcher] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 20:38:13,127] - [    INFO] - [   root] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - User 249824300 pressed the 'Share Referral Link' button
[2024-06-16 20:38:13,298] - [    INFO] - [aiogram.event] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Update id=396828941 is handled. Duration 173 ms by bot id=7025856738
[2024-06-16 20:38:14,911] - [    INFO] - [aiogram.event] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Update id=396828942 is handled. Duration 295 ms by bot id=7025856738
[2024-06-16 20:38:17,174] - [    INFO] - [aiogram.event] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Update id=396828943 is handled. Duration 75 ms by bot id=7025856738
[2024-06-16 21:04:23,528] - [ WARNING] - [aiogram.dispatcher] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Received SIGINT signal
[2024-06-16 21:04:23,529] - [    INFO] - [aiogram.dispatcher] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 21:04:23,529] - [    INFO] - [aiogram.dispatcher] - [268ec6d3-0203-41e8-97e0-51c5a0016d65] - Polling stopped
[2024-06-16 23:13:28,590] - [ WARNING] - [   root] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Starting connection
[2024-06-16 23:13:28,592] - [ WARNING] - [   root] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Connection established
[2024-06-16 23:13:28,592] - [    INFO] - [aiogram.dispatcher] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Start polling
[2024-06-16 23:13:28,639] - [    INFO] - [aiogram.dispatcher] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:14:05,236] - [    INFO] - [aiogram.event] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Update id=396828944 is not handled. Duration 30427 ms by bot id=7025856738
[2024-06-16 23:14:05,236] - [   ERROR] - [aiogram.event] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Cause exception while process update id=396828944 by bot id=7025856738
ServerSelectionTimeoutError: mongo_needify:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 666f4768ad4b7cbad0e2c073, topology_type: Unknown, servers: [<ServerDescription ('mongo_needify', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_needify:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/core/handlers.py", line 22, in command_start
    exist_user = await user_manager.get_user(message.from_user.id)
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/users/manager.py", line 31, in get_user
    user = await self.database.get_user(user_id=user_id)
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/users/database.py", line 14, in get_user
    user = await self.collection.find_one({"user_id": user_id})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/collection.py", line 1495, in find_one
    for result in cursor.limit(-1):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1425, in _run_operation
    return self._retryable_read(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1534, in _retryable_read
    return self._retry_internal(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1501, in _retry_internal
    ).run()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 2347, in run
    return self._read() if self._is_read else self._write()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 2477, in _read
    self._server = self._get_server()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 2433, in _get_server
    return self._client._select_server(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1316, in _select_server
    server = topology.select_server(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/topology.py", line 368, in select_server
    server = self._select_server(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pymongo/topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo_needify:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 666f4768ad4b7cbad0e2c073, topology_type: Unknown, servers: [<ServerDescription ('mongo_needify', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_needify:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-06-16 23:14:10,435] - [ WARNING] - [aiogram.dispatcher] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Received SIGINT signal
[2024-06-16 23:14:10,436] - [    INFO] - [aiogram.dispatcher] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:14:10,436] - [    INFO] - [aiogram.dispatcher] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Polling stopped
[2024-06-16 23:14:10,689] - [    INFO] - [aiogram.event] - [cd3cb4f6-7a13-4d90-849c-21c6e5ac476d] - Update id=396828945 is not handled. Duration 24818 ms by bot id=7025856738
[2024-06-16 23:14:51,215] - [ WARNING] - [   root] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Starting connection
[2024-06-16 23:14:51,215] - [ WARNING] - [   root] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Connection established
[2024-06-16 23:14:51,216] - [    INFO] - [aiogram.dispatcher] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Start polling
[2024-06-16 23:14:51,255] - [    INFO] - [aiogram.dispatcher] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:14:53,785] - [   ERROR] - [   root] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Referrer id is empty
[2024-06-16 23:14:53,948] - [    INFO] - [aiogram.event] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Update id=396828946 is handled. Duration 179 ms by bot id=7025856738
[2024-06-16 23:15:48,732] - [ WARNING] - [aiogram.dispatcher] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Received SIGINT signal
[2024-06-16 23:15:48,733] - [    INFO] - [aiogram.dispatcher] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:15:48,733] - [    INFO] - [aiogram.dispatcher] - [8e39938a-06d8-4115-831a-10a98d66ea41] - Polling stopped
[2024-06-16 23:15:51,428] - [ WARNING] - [   root] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Starting connection
[2024-06-16 23:15:51,428] - [ WARNING] - [   root] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Connection established
[2024-06-16 23:15:51,429] - [    INFO] - [aiogram.dispatcher] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Start polling
[2024-06-16 23:15:51,488] - [    INFO] - [aiogram.dispatcher] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:15:53,465] - [   ERROR] - [   root] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Referrer id is empty
[2024-06-16 23:15:53,642] - [    INFO] - [aiogram.event] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Update id=396828947 is handled. Duration 184 ms by bot id=7025856738
[2024-06-16 23:17:14,528] - [ WARNING] - [aiogram.dispatcher] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Received SIGINT signal
[2024-06-16 23:17:14,529] - [    INFO] - [aiogram.dispatcher] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:14,529] - [    INFO] - [aiogram.dispatcher] - [a107456c-3dbc-4f2c-8023-f5523f9b6e11] - Polling stopped
[2024-06-16 23:17:17,150] - [ WARNING] - [   root] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Starting connection
[2024-06-16 23:17:17,150] - [ WARNING] - [   root] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Connection established
[2024-06-16 23:17:17,150] - [    INFO] - [aiogram.dispatcher] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Start polling
[2024-06-16 23:17:17,190] - [    INFO] - [aiogram.dispatcher] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:19,865] - [    INFO] - [aiogram.event] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Update id=396828948 is not handled. Duration 12 ms by bot id=7025856738
[2024-06-16 23:17:19,865] - [   ERROR] - [aiogram.event] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Cause exception while process update id=396828948 by bot id=7025856738
ValidationError: 1 validation error for ReferrerSchema
referral_rule_name
  Input should be a valid string [type=string_type, input_value=<coroutine object get_act...ral_name at 0x1149fe6c0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/core/handlers.py", line 44, in command_start
    await user_manager.add_user(user=message.from_user)
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/users/manager.py", line 17, in add_user
    referral_schema = ReferrerSchema(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReferrerSchema
referral_rule_name
  Input should be a valid string [type=string_type, input_value=<coroutine object get_act...ral_name at 0x1149fe6c0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
[2024-06-16 23:17:40,349] - [ WARNING] - [aiogram.dispatcher] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Received SIGINT signal
[2024-06-16 23:17:40,350] - [    INFO] - [aiogram.dispatcher] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:40,351] - [    INFO] - [aiogram.dispatcher] - [104525e2-6fc0-4b77-b670-56eb4397d70c] - Polling stopped
[2024-06-16 23:17:42,924] - [ WARNING] - [   root] - [17dc550f-57bb-4201-8240-80d919c318c8] - Starting connection
[2024-06-16 23:17:42,924] - [ WARNING] - [   root] - [17dc550f-57bb-4201-8240-80d919c318c8] - Connection established
[2024-06-16 23:17:42,924] - [    INFO] - [aiogram.dispatcher] - [17dc550f-57bb-4201-8240-80d919c318c8] - Start polling
[2024-06-16 23:17:42,971] - [    INFO] - [aiogram.dispatcher] - [17dc550f-57bb-4201-8240-80d919c318c8] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:52,343] - [ WARNING] - [aiogram.dispatcher] - [17dc550f-57bb-4201-8240-80d919c318c8] - Received SIGINT signal
[2024-06-16 23:17:52,345] - [    INFO] - [aiogram.dispatcher] - [17dc550f-57bb-4201-8240-80d919c318c8] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:52,345] - [    INFO] - [aiogram.dispatcher] - [17dc550f-57bb-4201-8240-80d919c318c8] - Polling stopped
[2024-06-16 23:17:54,636] - [ WARNING] - [   root] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Starting connection
[2024-06-16 23:17:54,636] - [ WARNING] - [   root] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Connection established
[2024-06-16 23:17:54,636] - [    INFO] - [aiogram.dispatcher] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Start polling
[2024-06-16 23:17:54,680] - [    INFO] - [aiogram.dispatcher] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:17:56,436] - [    INFO] - [aiogram.event] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Update id=396828949 is not handled. Duration 8 ms by bot id=7025856738
[2024-06-16 23:17:56,437] - [   ERROR] - [aiogram.event] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Cause exception while process update id=396828949 by bot id=7025856738
ValidationError: 5 validation errors for UserModelSchema
_id
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
balance
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
created
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
updated
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
last_activity
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/core/handlers.py", line 44, in command_start
    await user_manager.add_user(user=message.from_user)
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/users/manager.py", line 20, in add_user
    user_schema = UserModelSchema(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 5 validation errors for UserModelSchema
_id
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
balance
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
created
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
updated
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
last_activity
  Field required [type=missing, input_value={'chat_id': 249824300, 'f...al_rule_name='default')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
[2024-06-16 23:18:49,033] - [ WARNING] - [aiogram.dispatcher] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Received SIGINT signal
[2024-06-16 23:18:49,035] - [    INFO] - [aiogram.dispatcher] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:18:49,035] - [    INFO] - [aiogram.dispatcher] - [ddab73e1-0cc6-458a-8e2d-c317ec50215f] - Polling stopped
[2024-06-16 23:18:51,643] - [ WARNING] - [   root] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Starting connection
[2024-06-16 23:18:51,643] - [ WARNING] - [   root] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Connection established
[2024-06-16 23:18:51,643] - [    INFO] - [aiogram.dispatcher] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Start polling
[2024-06-16 23:18:51,701] - [    INFO] - [aiogram.dispatcher] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:18:52,507] - [    INFO] - [aiogram.event] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Update id=396828950 is handled. Duration 220 ms by bot id=7025856738
[2024-06-16 23:19:00,988] - [    INFO] - [aiogram.event] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Update id=396828951 is handled. Duration 79 ms by bot id=7025856738
[2024-06-16 23:20:08,014] - [ WARNING] - [aiogram.dispatcher] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Received SIGINT signal
[2024-06-16 23:20:08,014] - [    INFO] - [aiogram.dispatcher] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:20:08,015] - [    INFO] - [aiogram.dispatcher] - [90b2718a-e6f3-48a6-8905-cc2752cea4e9] - Polling stopped
[2024-06-16 23:20:10,809] - [ WARNING] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Starting connection
[2024-06-16 23:20:10,810] - [ WARNING] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Connection established
[2024-06-16 23:20:10,810] - [    INFO] - [aiogram.dispatcher] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Start polling
[2024-06-16 23:20:10,855] - [    INFO] - [aiogram.dispatcher] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:20:12,095] - [    INFO] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Adding user 249824300 to database
[2024-06-16 23:20:12,096] - [    INFO] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - User 249824300 added to database
[2024-06-16 23:20:12,263] - [    INFO] - [aiogram.event] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Update id=396828952 is handled. Duration 178 ms by bot id=7025856738
[2024-06-16 23:20:19,590] - [    INFO] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Adding user 249824300 to database
[2024-06-16 23:20:19,592] - [    INFO] - [   root] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - User 249824300 added to database
[2024-06-16 23:20:19,656] - [    INFO] - [aiogram.event] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Update id=396828953 is handled. Duration 75 ms by bot id=7025856738
[2024-06-16 23:21:11,051] - [ WARNING] - [aiogram.dispatcher] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Received SIGINT signal
[2024-06-16 23:21:11,052] - [    INFO] - [aiogram.dispatcher] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:21:11,053] - [    INFO] - [aiogram.dispatcher] - [d89a1937-e0fa-413f-8c18-9b841f4dc41b] - Polling stopped
[2024-06-16 23:21:13,695] - [ WARNING] - [   root] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Starting connection
[2024-06-16 23:21:13,695] - [ WARNING] - [   root] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Connection established
[2024-06-16 23:21:13,696] - [    INFO] - [aiogram.dispatcher] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Start polling
[2024-06-16 23:21:13,734] - [    INFO] - [aiogram.dispatcher] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:21:15,676] - [    INFO] - [aiogram.event] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Update id=396828954 is not handled. Duration 8 ms by bot id=7025856738
[2024-06-16 23:21:15,676] - [   ERROR] - [aiogram.event] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Cause exception while process update id=396828954 by bot id=7025856738
ValidationError: 1 validation error for UserModelSchema
_id
  Input should be a valid string [type=string_type, input_value=ObjectId('666f48ac569948430ec53530'), input_type=ObjectId]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/core/handlers.py", line 22, in command_start
    exist_user = await user_manager.get_user(message.from_user.id)
  File "/Users/creator/Documents/Projects/The-Open-Times/tbot/src/users/manager.py", line 36, in get_user
    return UserModelSchema(**user) if user else None
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/the_times_bot-r81YgV47-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for UserModelSchema
_id
  Input should be a valid string [type=string_type, input_value=ObjectId('666f48ac569948430ec53530'), input_type=ObjectId]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
[2024-06-16 23:21:22,578] - [ WARNING] - [aiogram.dispatcher] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Received SIGINT signal
[2024-06-16 23:21:22,579] - [    INFO] - [aiogram.dispatcher] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:21:22,579] - [    INFO] - [aiogram.dispatcher] - [54145e9d-beb0-4e42-a092-c7cca02da97e] - Polling stopped
[2024-06-16 23:21:25,075] - [ WARNING] - [   root] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Starting connection
[2024-06-16 23:21:25,075] - [ WARNING] - [   root] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Connection established
[2024-06-16 23:21:25,075] - [    INFO] - [aiogram.dispatcher] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Start polling
[2024-06-16 23:21:25,120] - [    INFO] - [aiogram.dispatcher] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:21:28,733] - [    INFO] - [aiogram.event] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Update id=396828955 is handled. Duration 190 ms by bot id=7025856738
[2024-06-16 23:21:33,707] - [    INFO] - [aiogram.event] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Update id=396828956 is not handled. Duration 2 ms by bot id=7025856738
[2024-06-16 23:23:15,379] - [ WARNING] - [aiogram.dispatcher] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Received SIGINT signal
[2024-06-16 23:23:15,381] - [    INFO] - [aiogram.dispatcher] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:23:15,381] - [    INFO] - [aiogram.dispatcher] - [b505e5c5-715e-4fb7-9e6f-9083fe2a24b9] - Polling stopped
[2024-06-16 23:23:17,757] - [ WARNING] - [   root] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Starting connection
[2024-06-16 23:23:17,757] - [ WARNING] - [   root] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Connection established
[2024-06-16 23:23:17,757] - [    INFO] - [aiogram.dispatcher] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Start polling
[2024-06-16 23:23:17,800] - [    INFO] - [aiogram.dispatcher] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Run polling for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:23:19,769] - [    INFO] - [aiogram.event] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Update id=396828957 is handled. Duration 196 ms by bot id=7025856738
[2024-06-16 23:23:34,267] - [ WARNING] - [aiogram.dispatcher] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Received SIGINT signal
[2024-06-16 23:23:34,270] - [    INFO] - [aiogram.dispatcher] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Polling stopped for bot @needify_bot id=7025856738 - 'Needify'
[2024-06-16 23:23:34,270] - [    INFO] - [aiogram.dispatcher] - [3a6ce042-6753-4ffd-a858-ffe46c98662e] - Polling stopped
